TechTrawl/config/routes.rb
Rails.application.routes.draw do
   
  resources :users, only: [:new, :create, :destroy, :update, :edit]
  resource :session, only: [:new, :create, :destroy]
  
  resources :tags, shallow: true, only: [:destroy, :create]

  resources :companies 
  
  resources :articles, only: [:index, :create]

  resources :events, only: [:index, :create, :destroy]

  get '/', to: 'companies#index', as: 'home'
  get '/about', to: 'about#index'

  namespace :admin do
    
    resources :dashboard, only: [:index]
    get '/dashboard/organizations', to:'dashboard#organizations'
    get '/dashboard/technologies', to:'dashboard#technologies'
    get '/dashboard/users', to:'dashboard#users'
    get '/dashboard/events', to: 'dashboard#events'

  end
end

TechTrawl/app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authorize_admin!

  def index
    @users = User.all
  end

  def organizations
    @companies = Company.all
  end

  def technologies
    @tag = Tag.new
    @tags = Tag.all
  end

  def users
    @users = User.all
  end

  def events
    @events = Event.all
  end

  private
  def authorize_admin!
    unless current_user.admin?
      flash[:danger] = "Access Denied"
      redirect_to home_path
    end
  end
end

TechTrawl/app/views/admin/dashboard/events.html.erb
<h1>Events</h1>

<div class="card mb-4">
<table class="table container table-hover table-borderless">
  <thead>
    <tr class="table-success">
      <th scope="col" style="border-radius:8px 0px 0px 0px">Meetup Id</th>
      <th scope="col" style="border-radius:0px 8px 0px 0px">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
    <tr>
      <td style="border-right: 1px solid #e2e8eb"><%= event.urlname %></td>
      <td>
        <%= link_to('remove', event_path(event.id),
        method: :delete, class:"text-warning")%>
      </td>    
    </tr>
    <%end%>
  </tbody>
</table>
</div>

TechTrawl/app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>

<div class="card mb-4">
<table class="table table-borderless table-hover">
  <thead>
    <tr class="table-success">
      <th style="border-radius:8px 0px 0px 0px">First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Created At</th>
      <th style="border-radius:0px 8px 0px 0px">Admin?</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= time_ago_in_words(user.created_at) %></td>
        <td><%= user.admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

TechTrawl/app/views/admin/dashboard/organizations.html.erb
<h1>Organizations <span>
  <%= link_to('add', new_company_path, class:"btn btn-outline-dark")%>
</span></h1>

<div class="card mb-4">
<table class="table container table-hover table-borderless">
  <thead>
    <tr class="table-success">
      <th scope="col" style="border-radius:8px 0px 0px 0px">Organization Name</th>
      <th scope="col">Published</th>
      <th scope="col" style="border-radius:0px 8px 0px 0px">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td style="border-right: 1px solid #e2e8eb"><%= company.name %></td>
      <td style="border-right: 1px solid #e2e8eb"><%=company.published%></td> 
      <td>
        <%= link_to('show', company_path(company.id), class:"text-success mr-4")%>
        <%= link_to('edit', edit_company_path(company.id), class:"text-primary mr-4")%>
        <%= link_to('remove', company_path(company.id),
        method: :delete, class:"text-danger")%>
      </td>    
    </tr>
    <%end%>
  </tbody>
</table>
</div>

TechTrawl/app/views/admin/dashboard/technologies.html.erb
<h1>Technologies</h1>

<div class="container" style="margin-bottom:72px;">
<%= form_for @tag do |t| %>
  <div>
    <%= t.label :name, class:"mt-3" %>
    <%= t.text_field :name, class:"form-control" %>
  </div>

  <%= t.submit "Add", class:"btn btn-outline-dark mt-2 mb-4", style:"float:right" %>
<%end%>
</div>

 <div class="card mb-4">
<table class="table table-borderless container table-hover">
  <thead>
    <tr class="table-success">
      <th scope="col" style="border-radius:8px 0px 0px 0px">Technology Name</th>
      <th scope="col" style="border-radius:0px 8px 0px 0px">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
    <tr>
      <td style="border-right: 1px solid #e2e8eb"><%= tag.name %></td>
      <td> <%= link_to('remove', tag_path(tag.id),
      method: :delete, class:"text-warning")%></td>
    </tr>
    <%end%>
  </tbody>
</table>
</div>

TechTrawl/app/views/admin/dashboard/users.html.erb
<h1>Users</h1>

<div class="card mb-4">
<table class="table table-borderless container table-hover">
  <thead>
    <tr class="table-success"> 
      <th scope="col" style="border-radius:8px 0px 0px 0px">Name</th>
      <th scope="col">email</th>
      <th scope="col">Organization</th>
      <th scope="col" style="border-radius:0px 8px 0px 0px">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td style="border-right: 1px solid #e2e8eb"><%= user.first_name %></td>
      <td style="border-right: 1px solid #e2e8eb"><%=user.email%></td> 
      <td style="border-right: 1px solid #e2e8eb"><%=user.company_id%></td>       
      <td>
        <%= link_to('edit', edit_user_path(user), class:"mr-3")%>
        <%= link_to('remove', user_path(user.id),
        method: :delete, class:"text-warning")%>
      </td>    
    </tr>
    <%end%>
  </tbody>
</table>
</div>