TechTrawl/config/routes.rb
Rails.application.routes.draw do
   
  resources :users, only: [:new, :create, :destroy, :update, :edit]
  resource :session, only: [:new, :create, :destroy]
  
  resources :tags, shallow: true, only: [:destroy, :create]

  resources :companies 
  
  resources :articles, only: [:index, :create]

  resources :events, only: [:index, :create, :destroy]

  get '/', to: 'companies#index', as: 'home'
  get '/about', to: 'about#index'

  namespace :admin do
    
    resources :dashboard, only: [:index]
    get '/dashboard/organizations', to:'dashboard#organizations'
    get '/dashboard/technologies', to:'dashboard#technologies'
    get '/dashboard/users', to:'dashboard#users'
    get '/dashboard/events', to: 'dashboard#events'

  end
end

TechTrawl/app/models/company.rb
class Company < ApplicationRecord
    belongs_to :user
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    has_many :events, dependent: :nullify
    has_many :articles, dependent: :nullify

    geocoded_by :full_address
    after_validation :geocode, :if => :address_changed?

    validates(:name, presence: true, uniqueness: true)

    #scope :tech_team, -> (number) { where("tech_team >= 10", number }
    #the above code is Jocelyn trying to apply a search filter

    def self.search(term)
        @companies = 
        if term 
            where("name ILIKE ?", "%#{term}%").order("name ASC")
        else 
            order("name ASC")
        end
    end

    def full_address
        [address, postal_code].compact.join(', ')
    end
end

TechTrawl/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :authorize_user!, only: [:create, :edit, :update]

    def index
        @companies = Company.search(params[:term]).order(name: :asc).paginate(:per_page => 10, :page => params[:page])
        @company = Company.all 

        @hash = Gmaps4rails.build_markers(@company) do |company, marker|
            marker.lat company.latitude
            marker.lng company.longitude
          end
    end

    def new
        @company = Company.new
    end
    
    def create
        @company = Company.new company_params
        @company.user = current_user 
      
        # render json: @company
        if @company.save
            flash[:success] = "Company created!"
            redirect_to company_path(@company)
        else
            render "companies/new"
        end
        
    end
    
    def edit
        @company = Company.find params[:id]
    end

    def update
        @company = Company.find params[:id]
        if @company.update(company_params)
            redirect_to company_path(@company.id)
          else
            render :edit
        end 
    end

    def show
         @company = Company.find(params[:id])
        
    end

=begin     def search(query)
        where("name ILIKE ?", "%#{query}%")
        .or(where("tag ILIKE ?", "%#{query}%"))
    end 
=end
    def destroy
        @company ||= Company.find params[:id]

        @company.destroy

        redirect_to admin_dashboard_organizations_path
    end

    private
    def company_params
        params.require(:company).permit(:name, 
            :address, 
            :postal_code,
            :overview, 
            :employees, 
            :tech_team, 
            :website,       
            :twitter,
            :logo, 
            :published, 
            :user_id,
            :term,
            tag_ids: [])
    end

    def authorize_user!
        unless can?(:crud, @company)
            flash[:danger] = "Access Denied!"
            redirect_to company_path(@company)
        end
    end
end




    



   

     

   

TechTrawl/app/views/companies/_form.html.erb
<div style="margin-bottom:56px;">

<%= form_for(@company) do |c|%>
    
    <% if @company.errors.present? %>
        <p>
        <%= @company.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <div>
        <%=c.label(:name, class:"mt-3")%>
        <%=c.text_field :name, class:"form-control"%>
    </div>

    <div>
        <%=c.label(:address, class:"mt-3")%>
        <%=c.text_field :address, class:"form-control"%>
    </div>

    <div>
        <%=c.label(:postal_code, class:"mt-3")%>
        <%=c.text_field :postal_code, class:"form-control"%>
    </div>

    <div>
        <%=c.label(:overview, class:"mt-3")%>
        <%=c.text_area :overview, class:"form-control"%>
    </div>

    <div>
        <%=c.label(:employees, class:"mt-3")%>
        <%=c.number_field :employees, class:"form-control"%>
    </div>

    <div>
        <%=c.label(:tech_team, class:"mt-3")%>
        <%=c.number_field :tech_team, class:"form-control"%>
    </div>

    <div>
        <%=c.label(:website, class:"mt-3")%>
        <%=c.text_field :website, class:"form-control"%>
    </div>

    <div>
        <%= c.label(:tags, class:"mt-3") %>
        <%= c.collection_select(
        :tag_ids,
        Tag.order(name: :asc),
        :id,
        # :humanized_name,
        :name,
        {},
        {multiple: :true, class: 'chosen-select'}
        ) %>
    </div>

    <div>
        <%=c.label :twitter, class:"mt-3"%>
        <%=c.text_field :twitter, class:"form-control"%>
    </div>

    <div>
        <%=c.label :logo, class:"mt-3"%>
        <%=c.text_field :logo, class:"form-control"%>
    </div>

    <% if current_user&.admin?%>
        <div>
            <%=c.label(:published, class:"mt-3")%>
            <%=c.check_box(:published, class:"mt-3")%>
        </div>
    <%end%>

    <%= c.submit nil, class:"btn btn-outline-dark", style:"float:right;" %>

<%end%>

</div>

TechTrawl/app/views/companies/_list.html.erb
<div class="container">
    <div class="row">
<% @companies.each do |company| %>
<div class="col-lg-4 col-md-6 col-sm-12">
    <div class="card mt-4 mb-4 h-75">
        <div class="card-body">
            <%= image_tag company.logo, style:"width: 100px; float:left;" %>
            <div class="card-text text-right align-bottom" style="float:right;">
                <%= link_to( 
                    company.name, 
                    company_path(company), 
                    class: "text-dark h4") %>
                <p class="text-right"><%= company.employees %> Employees<br />
                <%= company.tech_team %> in Tech Team<br />
                <%= link_to company.website, "#{company.website}" %></p>
            </div>
            </div>
        </div>
    </div>
<% end %>
</div>
</div>


<%= will_paginate @companies, class:"text-center my-2 text-dark page-link rounded" %>

TechTrawl/app/views/companies/edit.html.erb
<h2>Edit Companies</h2>

<%= render "form" %>

TechTrawl/app/views/companies/index.html.erb
<div class="container">
<h2 class="my-3 text-center">Directory</h2>

<div style="width: 100%">
  <div id="map" style="width: 700px; height: 400px; margin: auto">
</div>
<br>

<div class="container" style="margin-bottom: 72px;">
  <%= form_tag(companies_path, method: :get) do %>
    <%= text_field_tag :term, params[:term], class:"form-control" %>
    <%= submit_tag "Search", name: nil, class:"btn btn-outline-dark mt-2", style:"float: right;" %>
    <%= link_to "Clear", companies_path, class:"btn btn-outline-dark mt-2 mr-2", style:"float: right;" %>
  <% end %>

  <div class="dropdown mt-2 mr-2" style="float:right">
    <button class="btn btn-outline-success dropdown-toggle" type="button" data-toggle="dropdown">Team Size
    <span class="caret"></span></button>
    <ul class="dropdown-menu ">
      <li><a href="#" style="text-decoration:none"><p class="text-center lead list-group-item-action text-success">10</p></a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">20</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">50</a></li>
    </ul>
  </div>

  <div class="dropdown mt-2 mr-2" style="float:right">
    <button class="btn btn-outline-success dropdown-toggle" type="button" data-toggle="dropdown">Team Stack
    <span class="caret"></span></button>
    <ul class="dropdown-menu ">
      <li><a href="#" style="text-decoration:none"><p class="text-center lead list-group-item-action text-success">Autocoder</p></a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">BrightScript</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">Coffeescript</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">Elixir</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">Express</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">Javascript</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">Postgres</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">Rails</a></li>
      <li><a href="#" style="text-decoration:none" class="text-success"><p class="text-center lead list-group-item-action">Ruby</a></li>
    </ul>
  </div>
</div>

</div>

</div>

<%= render "list" %>

</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: { maxZoom: 20}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

TechTrawl/app/views/companies/new.html.erb
<h2>New Organization</h2>

<%= render "form" %>

TechTrawl/app/views/companies/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-3">
            <img src="<%= @company.logo %>" style="width: 200px">
        </div>
        <div class="col-6">
            <div class="text-left">
                <h2 style="display:inline"><%= @company.name %></h2>
                <%= link_to "(visit website)", @company.website %>
                <p><%= @company.overview %></p>
                <ul style="list-style: none; padding: 0px;">
                    <li><strong>Tags:</strong>
                    <%= @company.tags.order(name: :asc).map{ |t| t.name}.join(', ') %>
                    </li>
                    <li><strong>Team Size:</strong> <%= @company.employees %> </li>
                    <li><strong>Tech Team:</strong> <%= @company.tech_team %> </li>
                    <li><strong>Manager:</strong> <%= @company.user.full_name %></li>
                </ul>
            </div>
        </div>
    </div>
        <hr />
        <div class="row" style="margin-top: 24px;">
            <div class="col-5">
                <a class="twitter-timeline" data-tweet-limit="2" href="<%= @company.twitter %>">Tweets by TwitterDev</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
            <div class="col-4">
            <h3 style="margin-top:12px;"> <%= @company.name %> News: </h3>
            <% @company.articles.each do |article| %>
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="<%= article.url_to_image %>">
                    <div class="card-body">
                        <p class="card-text"><%= link_to article.title, article.url %></p>
                    </div>
                </div>
                <br>
            <% end %>
            </div>
            <div class="col-3">
                <h3 style="margin-top:12px;"> <%= @company.name %> Events: </h3>
                <% @company.events.each do |event| %>
                    <p style="border: 1px solid #e2e8eb; border-radius: 8px;" class="p-2 text-center">
                    <%= link_to event.name, event.link %><br />
                    <%= event.start_time.strftime("%B %d, %Y") %>
                    </p>
                <% end %>
            </div>
        </div>
    </div>
</div>