TechTrawl/config/routes.rb
Rails.application.routes.draw do
   
  resources :users, only: [:new, :create, :destroy, :update, :edit]
  resource :session, only: [:new, :create, :destroy]
  
  resources :tags, shallow: true, only: [:destroy, :create]

  resources :companies 
  
  resources :articles, only: [:index, :create]

  resources :events, only: [:index, :create, :destroy]

  get '/', to: 'companies#index', as: 'home'
  get '/about', to: 'about#index'

  namespace :admin do
    
    resources :dashboard, only: [:index]
    get '/dashboard/organizations', to:'dashboard#organizations'
    get '/dashboard/technologies', to:'dashboard#technologies'
    get '/dashboard/users', to:'dashboard#users'
    get '/dashboard/events', to: 'dashboard#events'

  end
end

TechTrawl/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :company

  validates :name, presence: true
  validates :meetup_id, uniqueness: true

  def self.search(term)
    @companies = 
    if term 
        where("name ILIKE ?", "%#{term}%").order("name ASC")
    else 
        order("name ASC")
    end
end

end

TechTrawl/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event
      .search(params[:search])
      .order(start_time: :asc)
      .paginate(:per_page => 10, :page => params[:page])

    event_api = EventRetriever.new.events

    event_api['events'].each do |event|
      event = Event.new(
        meetup_id: event["id"],
        name: event["name"],
        start_time: event["local_date"],
        end_time: event["local_date"],
        company_id: Company.all.sample.id,
        urlname: event["group"]["urlname"],
        link: event["link"]
      )
    if event.save
    end
    end
  end

  def destroy
    @event ||= Event.find params[:id]

    @event.destroy

    redirect_to admin_dashboard_events_path
  end
end

TechTrawl/app/views/events/index.html.erb
<div class="container">
<h2 class="text-center">Events</h2>

  <%= month_calendar events: @events do |date, event| %>
    <%= date.day %>

    <% event.each do |e| %>
      <div  style="font-size: 0.8rem; width:">
        <%= link_to e.name, e.link, class:"text-dark border-success" %>
      </div>
    <% end %>
  <% end %>

<div class="container">
<%= form_tag events_path, :method => 'get' do %>
    <%= text_field_tag :search, nil, class:"form-control" %>
    <%= submit_tag "Search", :name => nil, class:"btn btn-outline-dark mt-2", style:"float: right;" %>
    <%= link_to "Clear", events_path, class:"btn btn-outline-dark mt-2 mr-2", style:"float: right;" %>
<% end %>
</div>

<div class="container-fluid" style="margin-top: 72px;">
  <ul class="list-group">
    <li class="list-group-item list-group-item-success">
    <h4>Upcoming Events</h4>
    </li>
      <% @events.each do |event| %>
        <li class="list-group-item">
        <%= link_to event.name, event.link, class:"text-dark" %>
          <span style="float:right">
            <%= event.start_time.strftime("%B %d, %Y") %>
          </span>
        </li>
      <% end %>
  </ul>
  </div>


<%= will_paginate @events, class:"text-center my-2 text-dark page-link rounded" %>
</div>