TechTrawl/config/routes.rb
Rails.application.routes.draw do
   
  resources :users, only: [:new, :create, :destroy, :update, :edit]
  resource :session, only: [:new, :create, :destroy]
  
  resources :tags, shallow: true, only: [:destroy, :create]

  resources :companies 
  
  resources :articles, only: [:index, :create]

  resources :events, only: [:index, :create, :destroy]

  get '/', to: 'companies#index', as: 'home'
  get '/about', to: 'about#index'

  namespace :admin do
    
    resources :dashboard, only: [:index]
    get '/dashboard/organizations', to:'dashboard#organizations'
    get '/dashboard/technologies', to:'dashboard#technologies'
    get '/dashboard/users', to:'dashboard#users'
    get '/dashboard/events', to: 'dashboard#events'

  end
end

TechTrawl/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTrawl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyBqcJW6abgbEww9CaIPbaQbal4tyI9TQa0"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a href="/" class="navbar-brand text-success">
        <%= image_tag 'TechTrawl_logo', style:"width: 52px" %>
        TechTrawl
      </a>
      <button 
      class="navbar-toggler" 
      type="button" 
      data-toggle="collapse" 
      data-target="#my-nav-menu" 
      aria-controls="navbarNav" 
      aria-expanded="false" 
      aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
     </button>
    <div 
    id="my-nav-menu" 
    class="collapse navbar-collapse justify-content-end">
      <div class="navbar-nav">

        <%= link_to(
          'Directory', 
          home_path, 
          class: "nav-item text-light btn-link mr-3 mt-1 lead"
          ) %>
        <%= link_to(
          'Events', 
          events_path, 
          class: "nav-item text-light btn-link mr-3 mt-1 lead"
          ) %>
        <%= link_to(
          'Articles', 
          articles_path, 
          class: "nav-item text-light btn-link mr-3 mt-1 lead"
          ) %>

      </div>
    </div>
  </nav>

     <% if current_user&.admin? %>
        <nav class="navbar navbar-expand-sm navbar-light" style="background-color: #e0eed0; padding-top:0px; padding-bottom:0px">
          <span class="navbar-brand text-dark" style="
    margin-right: 0px;"
>Admin Dashboard</span>
          <div class="navbar-nav m-auto">
            <ul class="nav">
              <li>
                <%= link_to('Organization', admin_dashboard_organizations_path, class: "nav-link text-dark btn-outline-success p-3") %>
              </li>
              <li>
                <%= link_to('Events', admin_dashboard_events_path, class: "nav-link text-dark btn-outline-success p-3") %>
              </li>
              <li>
                <%= link_to('Users', admin_dashboard_users_path, class: "nav-link text-dark btn-outline-success p-3") %>
              </li>
              <li>
                <%= link_to('Technologies', admin_dashboard_technologies_path, class: "nav-link text-dark btn-outline-success p-3") %>
              </li>
            </ul>
          </div>
        </nav>
      <% end %>



    <div class="container-fluid" style="padding:0px;">
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %> alert-dismissible fade show text-center">
        <%= message %>
      </div>
    <% end %>
    </div>

    <div class="container mt-4">
    <%= yield %>
    </div>

    <nav class="navbar navbar-expand-md bg-dark">
      <div class="container-fluid my-3 d-flex">
          <div class="flex-fill">
            <% if current_user.present? %>
              <p class="text-success">Hi, <%= current_user.first_name %></p>
              <%= link_to('Submit Organization', new_company_path, class:"text-light")%><br>
              <%= link_to(
                'Sign Out',
                  session_path,
                  method: :delete, 
                  class: "text-light"
              ) %>
            <% else %>
              <%= link_to('Sign In', new_session_path, class: "text-light") %>
              <br />
              <%= link_to('Sign Up', new_user_path, class: "text-light") %>
              <br />
              <%= link_to('About', about_path, class: "text-light") %>
            <% end %>
          </div>
            <div class="flex-fill">
                <%= image_tag 'TechTrawl_logo', style:"width: 64px; float: right" %>
            </div>
        </div>
    </nav>
    </footer>

  </body>
</html>